name: Evaluation 

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  unit_tests:
    # Name the Job
    name: Unit Tests
    # Set the type of machine to run on
    runs-on: self-hosted

    steps:
      # Checks out a copy of your repository on the self-hosted machine
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Test with pytest
        timeout-minutes: 1
        run: |
          pytest
  
